from __future__ import annotations

import json
import os
import random
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import cv2
import numpy as np
from moviepy.editor import VideoFileClip
from scenedetect import ContentDetector, detect
from scenedetect.video_splitter import split_video_ffmpeg

from app.models.task_models import VideoTaskRecord


@dataclass
class BoundaryDecision:
    should_merge: bool
    reasons: list[str]
    logs: list[str]


def run_scene_detection_and_split(
    video_record: VideoTaskRecord,
    task_workspace: str,
    base_media_url: str,
) -> list[dict[str, Any]]:
    """Step 1: Use PySceneDetect to detect and split original scene segments.

    What: Runs detect(...) to get scene list and split_video_ffmpeg(...) to export real files.
    Why: Requirement explicitly asks for true scene files instead of only time ranges.
    Result: Ordered original segments with exact float seconds and playable URLs.
    """
    source_path = video_record.sourceFilePath
    scene_output_dir = os.path.join(task_workspace, f"{video_record.videoId}_original_scenes")
    os.makedirs(scene_output_dir, exist_ok=True)

    video_record.append_log("info", "scene_detecting", "Starting PySceneDetect detection")
    scene_list = detect(source_path, ContentDetector())
    if not scene_list:
        scene_list = []
    video_record.append_log("info", "scene_detecting", f"PySceneDetect produced {len(scene_list)} scenes")

    # Explicit built-in PySceneDetect splitting call.
    split_video_ffmpeg(
        source_path,
        scene_list,
        output_dir=scene_output_dir,
        output_file_template="$VIDEO_NAME-Scene-$SCENE_NUMBER.mp4",
        show_progress=False,
    )
    video_record.append_log("success", "scene_detecting", "PySceneDetect split finished")

    generated_files = sorted(
        [os.path.join(scene_output_dir, file_name) for file_name in os.listdir(scene_output_dir) if file_name.endswith(".mp4")]
    )

    original_segments: list[dict[str, Any]] = []
    for index, generated_file in enumerate(generated_files):
        if index < len(scene_list):
            start_seconds = scene_list[index][0].get_seconds()
            end_seconds = scene_list[index][1].get_seconds()
        else:
            # fallback for safety if file count and scene count mismatch
            with VideoFileClip(generated_file) as segment_clip:
                start_seconds = original_segments[-1]["endSeconds"] if original_segments else 0.0
                end_seconds = start_seconds + float(segment_clip.duration)

        original_segments.append(
            {
                "originalSegmentIndex": index + 1,
                "startSeconds": float(start_seconds),
                "endSeconds": float(end_seconds),
                "durationSeconds": float(end_seconds - start_seconds),
                "sourceFilePath": generated_file,
                "sourceFileUrl": f"{base_media_url}/{Path(generated_file).relative_to(Path(task_workspace).parent.parent).as_posix()}",
            }
        )

    if not original_segments:
        raise RuntimeError("No original segments were generated by PySceneDetect split")

    return original_segments


def evaluate_boundary_continuity(left_segment: dict[str, Any], right_segment: dict[str, Any]) -> BoundaryDecision:
    """Apply 4 base continuity rules on adjacent segment boundary."""
    reasons: list[str] = []
    logs: list[str] = []
    merge_votes = 0

    with VideoFileClip(left_segment["sourceFilePath"]) as left_clip, VideoFileClip(right_segment["sourceFilePath"]) as right_clip:
        # Rule 1: audio boundary energy
        left_audio = left_clip.audio
        right_audio = right_clip.audio
        left_energy = 0.0
        right_energy = 0.0
        if left_audio is not None:
            left_chunk = left_audio.subclip(max(left_clip.duration - 0.4, 0), left_clip.duration).to_soundarray(fps=22050)
            left_energy = float(np.mean(np.abs(left_chunk)))
        if right_audio is not None:
            right_chunk = right_audio.subclip(0, min(0.4, right_clip.duration)).to_soundarray(fps=22050)
            right_energy = float(np.mean(np.abs(right_chunk)))
        if left_energy > 0.01 and right_energy > 0.01:
            merge_votes += 1
            reasons.append("audio_boundary_continuous")
        logs.append(f"Audio energy left={left_energy:.5f}, right={right_energy:.5f}")

        # Rule 2: frame similarity around boundary
        left_frame = left_clip.get_frame(max(left_clip.duration - 0.1, 0))
        right_frame = right_clip.get_frame(min(0.1, right_clip.duration))
        left_gray = cv2.cvtColor(left_frame.astype(np.uint8), cv2.COLOR_RGB2GRAY)
        right_gray = cv2.cvtColor(right_frame.astype(np.uint8), cv2.COLOR_RGB2GRAY)
        similarity_score = cv2.matchTemplate(left_gray, right_gray, cv2.TM_CCOEFF_NORMED)[0][0]
        if similarity_score > 0.80:
            merge_votes += 1
            reasons.append("boundary_frame_similarity")
        logs.append(f"Frame similarity score={similarity_score:.4f}")

        # Rule 3: motion continuity (optical flow magnitude diff)
        def motion_score(frame_a: np.ndarray, frame_b: np.ndarray) -> float:
            flow = cv2.calcOpticalFlowFarneback(
                cv2.cvtColor(frame_a.astype(np.uint8), cv2.COLOR_RGB2GRAY),
                cv2.cvtColor(frame_b.astype(np.uint8), cv2.COLOR_RGB2GRAY),
                None,
                0.5,
                3,
                15,
                3,
                5,
                1.2,
                0,
            )
            mag, _ = cv2.cartToPolar(flow[..., 0], flow[..., 1])
            return float(np.mean(mag))

        left_prev = left_clip.get_frame(max(left_clip.duration - 0.2, 0))
        left_last = left_clip.get_frame(max(left_clip.duration - 0.05, 0))
        right_first = right_clip.get_frame(min(0.05, right_clip.duration))
        right_next = right_clip.get_frame(min(0.2, right_clip.duration))
        left_motion = motion_score(left_prev, left_last)
        right_motion = motion_score(right_first, right_next)
        if abs(left_motion - right_motion) < 0.3:
            merge_votes += 1
            reasons.append("motion_continuity")
        logs.append(f"Motion left={left_motion:.4f}, right={right_motion:.4f}")

        # Rule 4: short segment protection
        if left_segment["durationSeconds"] < 1.8 or right_segment["durationSeconds"] < 1.8:
            if similarity_score > 0.6 or abs(left_motion - right_motion) < 0.45:
                merge_votes += 1
                reasons.append("short_segment_protection")
                logs.append("Short segment protection triggered")

    should_merge = merge_votes >= 2
    if should_merge:
        logs.append(f"Boundary merged with {merge_votes} positive rules")
    else:
        logs.append(f"Boundary kept split with only {merge_votes} positive rules")
    return BoundaryDecision(should_merge=should_merge, reasons=reasons, logs=logs)


def run_continuity_fix(
    video_record: VideoTaskRecord,
    original_segments: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Step 2: Merge adjacent scene segments using local continuity heuristics."""
    merged_candidates: list[list[dict[str, Any]]] = []
    current_group = [original_segments[0]]

    for index in range(len(original_segments) - 1):
        left_segment = original_segments[index]
        right_segment = original_segments[index + 1]
        boundary_decision = evaluate_boundary_continuity(left_segment, right_segment)

        for decision_log in boundary_decision.logs:
            video_record.append_log("info", "continuity_fixing", f"Boundary {index + 1}->{index + 2}: {decision_log}")

        if boundary_decision.should_merge:
            current_group.append(right_segment)
        else:
            merged_candidates.append(current_group)
            current_group = [right_segment]

    merged_candidates.append(current_group)

    candidate_segments: list[dict[str, Any]] = []
    for index, group in enumerate(merged_candidates):
        candidate_segments.append(
            {
                "candidateBusinessSegmentIndex": index + 1,
                "originalSegmentIndexRange": [group[0]["originalSegmentIndex"], group[-1]["originalSegmentIndex"]],
                "startSeconds": float(group[0]["startSeconds"]),
                "endSeconds": float(group[-1]["endSeconds"]),
                "durationSeconds": float(group[-1]["endSeconds"] - group[0]["startSeconds"]),
                "originalSegmentFiles": [item["sourceFilePath"] for item in group],
                "continuityFixReasons": ["merged" if len(group) > 1 else "kept_single"],
                "continuityFixLogs": [
                    f"Group contains original segments {group[0]['originalSegmentIndex']}~{group[-1]['originalSegmentIndex']}"
                ],
            }
        )

    video_record.append_log(
        "success",
        "continuity_fixing",
        f"Continuity fix reduced segments from {len(original_segments)} to {len(candidate_segments)}",
    )
    return candidate_segments


def run_grouping_with_dfs(video_record: VideoTaskRecord, candidates: list[dict[str, Any]]) -> tuple[list[list[dict[str, Any]]] | None, bool]:
    """Step 3: DFS/backtracking with pruning and 2376 cap."""
    video_record.append_log("info", "grouping", f"DFS started for {video_record.fileName}")

    if not candidates:
        video_record.append_log("error", "grouping", "No candidates provided for grouping")
        return None, False

    all_solutions: list[list[list[dict[str, Any]]]] = []
    max_solution_count = 2376
    cap_triggered = False

    def dfs(start_index: int, current_plan: list[list[dict[str, Any]]]) -> None:
        nonlocal cap_triggered
        if len(all_solutions) >= max_solution_count:
            cap_triggered = True
            return
        if start_index >= len(candidates):
            all_solutions.append([group[:] for group in current_plan])
            return

        current_duration = 0.0
        current_group: list[dict[str, Any]] = []

        for idx in range(start_index, len(candidates)):
            current_group.append(candidates[idx])
            current_duration += candidates[idx]["durationSeconds"]

            # Pruning: over 20s means too long for demo practical output.
            if current_duration > 20.0:
                break

            # Accept recommended or continuity-protected group.
            if 6.0 <= current_duration <= 14.0 or len(current_group) == 1:
                current_plan.append(current_group[:])
                dfs(idx + 1, current_plan)
                current_plan.pop()

    dfs(0, [])
    video_record.append_log("info", "grouping", f"DFS found {len(all_solutions)} legal solutions")
    if cap_triggered:
        video_record.append_log("warning", "grouping", "DFS reached 2376 solution cap and stopped early")

    if all_solutions:
        chosen_solution = random.choice(all_solutions)
        chosen_index = all_solutions.index(chosen_solution) + 1
        video_record.append_log("success", "grouping", f"Selected plan #{chosen_index}")
        return chosen_solution, False

    fallback_solution = [[candidate] for candidate in candidates]
    video_record.append_log("warning", "grouping", "No preferred solution found; fallback to continuity candidates")
    return fallback_solution, True


def merge_with_ffmpeg_concat(output_file_path: str, segment_files: list[str]) -> None:
    """Merge a set of mp4 files into one final business segment using ffmpeg concat."""
    concat_list_path = output_file_path + ".txt"
    with open(concat_list_path, "w", encoding="utf-8") as list_file:
        for file_path in segment_files:
            list_file.write(f"file '{os.path.abspath(file_path)}'\n")

    command = [
        "ffmpeg",
        "-y",
        "-f",
        "concat",
        "-safe",
        "0",
        "-i",
        concat_list_path,
        "-c",
        "copy",
        output_file_path,
    ]
    subprocess.run(command, check=True, capture_output=True)


def run_merge_and_export(
    video_record: VideoTaskRecord,
    task_workspace: str,
    grouping_plan: list[list[dict[str, Any]]],
    base_media_url: str,
) -> list[dict[str, Any]]:
    """Step 4: Merge grouped candidate segments into final business segments."""
    export_dir = os.path.join(task_workspace, f"{video_record.videoId}_final_segments")
    os.makedirs(export_dir, exist_ok=True)

    final_segments: list[dict[str, Any]] = []
    for final_index, group in enumerate(grouping_plan, start=1):
        source_files: list[str] = []
        for candidate in group:
            source_files.extend(candidate["originalSegmentFiles"])

        output_file_path = os.path.join(export_dir, f"final-segment-{final_index}.mp4")
        merge_with_ffmpeg_concat(output_file_path, source_files)
        video_record.append_log("info", "merging", f"ffmpeg concat generated final segment {final_index}")

        start_seconds = group[0]["startSeconds"]
        end_seconds = group[-1]["endSeconds"]
        duration_seconds = end_seconds - start_seconds
        exceeded = duration_seconds > 14.0

        final_segments.append(
            {
                "finalSegmentIndex": final_index,
                "startSeconds": float(start_seconds),
                "endSeconds": float(end_seconds),
                "durationSeconds": float(duration_seconds),
                "originalSegmentIndexRange": [
                    group[0]["originalSegmentIndexRange"][0],
                    group[-1]["originalSegmentIndexRange"][1],
                ],
                "candidateBusinessSegmentIndexRange": [
                    group[0]["candidateBusinessSegmentIndex"],
                    group[-1]["candidateBusinessSegmentIndex"],
                ],
                "originalSegmentFiles": source_files,
                "outputFilePath": output_file_path,
                "outputFileUrl": f"{base_media_url}/{Path(output_file_path).relative_to(Path(task_workspace).parent.parent).as_posix()}",
                "exceededRecommendedDurationBecauseOfContinuity": exceeded,
                "segmentSummaryText": "Continuity protected segment" if exceeded else "Within recommended duration",
            }
        )

    return final_segments


def write_debug_snapshot(task_workspace: str, filename: str, payload: dict[str, Any]) -> None:
    os.makedirs(task_workspace, exist_ok=True)
    with open(os.path.join(task_workspace, filename), "w", encoding="utf-8") as snapshot_file:
        json.dump(payload, snapshot_file, ensure_ascii=False, indent=2)
